<a href="https://colab.research.google.com/github/FANTASY000666/NUMPY/blob/main/numphy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Generating 1D and 2D arrays

In [ ]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [ ]:
b = np.array([[1,2], [3,4], [5,6]])

Populating array with sequence of numbers.

In [ ]:
seq1 = np.arange(5,12)
seq1

array([ 5,  6,  7,  8,  9, 10, 11])

In [ ]:
# Getting specific element in an array.
d = np.array([[1,2,3,4,5,6,7], [8,7,10,9,4,5,6]])
print("cell", d[1, 3])
print('\n')
print(d[:, 3]) # prints all elements in rows of column 3 : starts from index 0

print('\n')
print(d[1, :]) # prints all elements in columns in row 1: Starts from index 0

cell 9


[4 9]


[ 8  7 10  9  4  5  6]


Populates array random number

In [ ]:
# generating randoms integers between 50 and 100
random1 = np.random.randint(50, 101, 6)
print(random1)

[74 52 50 50 92 68]


In [ ]:
# Generating random float numbers 0.0 and 1.0 use np.random.random('pass in size of array')
random2 = np.random.rand(6)
print(random2)
print('\n')
random3 = np.random.random(5)
print(random3)

[0.42483035 0.7024887  0.28372826 0.85932627 0.86656013 0.12161735]


[0.74004158 0.49578896 0.65606685 0.22343958 0.14048228]


Broadcasting - NumPy uses a trick called broadcasting to virtually expand the smaller operand to dimensions compatible for linear algebra.

In [ ]:
random4 = random3 + 2.0
print(random4, '\n')

random5 = random3 * 3.0

[2.74004158 2.49578896 2.65606685 2.22343958 2.14048228] 



In [ ]:
# Finding the determinant of identity matrix 3
c = np.identity(3) # creates a matrix of identity 3
w = np.linalg.det(c) # finds the det of matrix c
inv = np.linalg.inv(c) # finds the inverse of matrix c
print(w, '\n') # prints the det, w
np.dot(inv, c) # multiply the inv of c with identity matrix c

1.0 



array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# solving a linear matrix Equation
a = np.array([[2,3], [4,-1]])
b = np.array([4,5])
solution = np.linalg.solve(a, b)
trace = np.trace(a)
eigenValues = np.linalg.eig(a)
print("eigenValues", eigenValues)
print("Trace", trace)
print("Solution", solution)

eigenValues (array([ 4.27491722, -3.27491722]), array([[ 0.79681209, -0.49436913],
       [ 0.60422718,  0.86925207]]))
Trace 1
Solution [1.35714286 0.42857143]


Create a linear dataset

In [ ]:
# first trial
feature = np.random.randint(6, 20)
print(feature)

label = 3*feature + 4
print(label)

8
28


In [ ]:
# second trial
feature1 = np.arange(6,21)
label1 = (feature1 * 3) + 4

print(feature1)
print("Label1 = ", label1)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Label1 =  [22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


Add Some Noise to the Dataset

In [ ]:
# first trial
noise = np.linspace(-2, 2, 15)
print(noise, '\n')

label2 = label1 + noise
print("label2 = ", label2)

[-2.         -1.71428571 -1.42857143 -1.14285714 -0.85714286 -0.57142857
 -0.28571429  0.          0.28571429  0.57142857  0.85714286  1.14285714
  1.42857143  1.71428571  2.        ] 

label2 =  [20.         23.28571429 26.57142857 29.85714286 33.14285714 36.42857143
 39.71428571 43.         46.28571429 49.57142857 52.85714286 56.14285714
 59.42857143 62.71428571 66.        ]


In [ ]:
# Second trial
noise2 = np.random.uniform(-2, 2, 15)
print(noise2, '\n')

label3 = label1 + noise2
print("Label3 = ", label3)

[ 0.52616028  1.62454622 -0.83935585 -1.96635809 -1.75845581 -0.62803543
  0.02220653 -1.9387268   0.89949226  1.50252637  1.91052829 -1.21447186
 -1.17464727  1.59371057 -0.44530816] 

Label3 =  [22.52616028 26.62454622 27.16064415 29.03364191 32.24154419 36.37196457
 40.02220653 41.0612732  46.89949226 50.50252637 53.91052829 53.78552814
 56.82535273 62.59371057 63.55469184]


In [ ]:
# Third trial
noise3 = (np.random.random([15]) * 4) - 2
print(noise3, '\n')

label4 = label1 + noise3
print(label4)

[-1.02409443 -0.41956442  1.24774876  0.52727618  1.52763105 -0.52852525
  1.01298765 -1.25040454  0.6617205   1.41288015 -0.26623739 -1.41403841
 -0.70683161  1.7107639   0.55325065] 

[20.97590557 24.58043558 29.24774876 31.52727618 35.52763105 36.47147475
 41.01298765 41.74959546 46.6617205  50.41288015 51.73376261 53.58596159
 57.29316839 62.7107639  64.55325065]
